name: deploy rust

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: deploy-rust
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Prepare download directory
        run: mkdir -p backend/target/release

      - name: Download latest backend binary
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: backend
          out-file-path: ./backend/target/release
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload backend deploy files
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_SSH_IP }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./backend/target/release/backend,./scripts/deploy_backend.py,./scripts/requirements.txt
          target: /tmp/

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_SSH_IP }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail

            python3 -m venv "$HOME/langample-venv"
            source "$HOME/langample-venv/bin/activate"
            python -m pip install -r /tmp/scripts/requirements.txt

            python3 /tmp/scripts/deploy_backend.py \
              --binary-path /tmp/backend/target/release/backend \
              --repo-url https://github.com/${{ github.repository }} \
              --api-key-chatgpt ${{ secrets.API_KEY_CHATGPT }} \
              --api-key-deepl ${{ secrets.API_KEY_DEEPL }} \
              --graphql-parent-path /langample/ \
              --panlex-sqlite-db-url ${{vars.PANLEX_DB_URL}} \
              --panlex-sqlite-db-path ${{vars.PANLEX_SQLITE_DB_PATH}}
